apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: safe-settings
  name: safe-settings
  namespace: default
spec:
  selector:
    matchLabels:
      app: safe-settings
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: safe-settings
    spec:
      containers:
      - image: ghcr.io/github/safe-settings:2.1.10
        name: safe-settings
        envFrom:
        - secretRef:
            name: app-env
